apiVersion: v1
data:
  init.sql: |-
    CREATE DATABASE db_product;
    CREATE DATABASE db_order;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: postgres
  name: postgres-cm0
