apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway-service
    spec:
      imagePullSecrets:
        - name: ocir-secret  # Si privé
      containers:
        - name: gateway-service
          image: eu-paris-1.ocir.io/axq1vfktkjkq/ms-gateway:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      