apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-service
  labels:
    app: keycloak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-service
  template:
    metadata:
      name: keycloak-service
      labels:
        app: keycloak-service
    spec:
      containers:
        - name: keycloak-service
          image: quay.io/keycloak/keycloak:23.0.1
          imagePullPolicy: IfNotPresent
          args:
            - start-dev
            - --http-port=9090
            - --hostname-strict=false

          ports:
            - containerPort: 9090
              protocol: TCP
      restartPolicy: Always
      