apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      name: product-service
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 0xbones1/ms-product:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP

          env:
            - name: POSTGRES_DB
              value: "jdbc:postgresql://postgres-service:5432/db_product"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
      restartPolicy: Always
      