name: products.yml
on:
  push:
    paths:
        - 'produit-service/**'
  pull_request:
    paths:
        - 'produit-service/**'

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'


        - name: Cache maven packages
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}--m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
                ${{ runner.os }}-m2-

        - name: Build with Maven
          run: mvn -f produit-service/pom.xml clean install

        - name: Run tests
          run: mvn -f produit-service/pom.xml test


    build-and-push:
      runs-on: ubuntu-latest
      needs: build-and-test
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: docker metadata
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: eu-paris-1.ocir.io/axq1vfktkjkq/ms-product
            tags: |
              type=ref,event=branch
#              type=ref,event=tag
#              type=sha
        - name: BuildX
          uses: docker/setup-buildx-action@v3

        - name: Login to docker hub
          uses: docker/login-action@v3
          with:
            registry: eu-paris-1.ocir.io
            username: ${{secrets.OCIR_USERNAME}}
            password: ${{secrets.OCIR_TOKEN}}
        - name: Build and push order image
          uses: docker/build-push-action@v4
          with:
            context: ./produit-service
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
            provenance: true
            sbom: true